### ISSUE TITLE
Signup flow enhancements

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#136]
- [ ] Unique validation for email, stack, app, and db #131
- [x] Improved plan selection UI #132
- [x] Loading indicator for saving of payment information in signup flow #133
- [x] Add header bar to signup flow #134
- [x] Signup flow progress indicator #135
- [ ] Platform accounts should use the Echosign API to automate contracting workflow #151

**Comment by sandersonet** [comment]
Closing in favor of two smaller remaining issues.
