### ISSUE TITLE
organizations section

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#188]
To do:

  * [x] members (pr: #187)
  * [x] invitations (#190)
    * [x] create new invitation (#198)
    * [x] resend existing invitation #204 
    * [x] destroy existing invitation #205 
  * [x] roles (https://github.com/aptible/diesel.aptible.com/issues/197);
    * [ ] edit permissions on a role (https://github.com/aptible/diesel.aptible.com/issues/225) (PR: #231)
    * [ ] edit a user's role memberships #228 
    * [ ] add an existing user to a role
    * [x] invite a new user to a role via email (https://github.com/aptible/diesel.aptible.com/issues/212)
    * [x] delete role (https://github.com/aptible/diesel.aptible.com/issues/206)
  * [ ] ~~environments (https://github.com/aptible/diesel.aptible.com/issues/201)~~
  * [ ] contact info
  * [ ] payment info
  * [ ] invoices

UI assurances of:

* [ ] We don't ever want to allow an organization to exist without at least 1 privileged user present
* [ ] When deleting a role, it's possible you are removing users from the organization. If any of the role members only belong to one role(this role), then we should prevent that role from being deleted and alert the user "You cannot delete this role as it is @mixonic 's and @sandersonet 's only role in the Aptible organization"
* [ ] When editing a user's set of roles you shouldn't be able to uncheck all of their roles:  [example](https://www.dropbox.com/s/sxk2br8ngsnp70m/Screenshot%202015-03-24%2011.55.06.png?dl=0)
Again, if you uncheck all of their roles, you'll effectively remove them from the organization and have to re-invite them.

**Comment by bantic** [comment]
this meta-issue is now a miletone: https://github.com/aptible/diesel.aptible.com/milestones/organizations

moved the UI assurances into #246
