### ISSUE TITLE
[meta] Full db/apps UI milestone

### ISSUE THREAD

**Issue by mixonic** [aptible/diesel.aptible.com#20]
* [ ] Staging deployment
* [ ] Forgot Password flow
* [ ] Email verification flow
* [ ] Create app styling
* [ ] Create db styling
* [ ] Auto-correct handles as typing (app, db)
* [ ] Create database needs size bar, type
* [ ] Style stack settings
* [ ] App show page
  * [x] List services #21 PR open (#22)
  * [ ] scale services, add vhosts #23 PR open (#25)
  * [x] History #24 PR open (#22)
  * [ ] Deprovision flow
* [ ] DB show page
  * [ ] Connection info
  * [ ] History

**Comment by bantic** [comment]
closing as this is covered by #51
