### ISSUE TITLE
Current Priorities

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#51]
### Completed

- [x] Invite acceptance functionality (@mixonic) https://github.com/aptible/diesel.aptible.com/pull/125
- [x] Signup flow
  - [x] Should restore users to previous state.  E.g. if user exists before submitting payment information, they should not be able to skip to stacks/show
  - [x] Currently, a stack is never actually created for a user when they enter payment information.  After a subscription is successfully created, we should also create a stack that matches the subscription plan.  We may need to update API to validate that stacks created have a valid type that matches the subscription level of the user.  E.g. If a user has only a development subscription, they shouldn't be able to provision a production stack.
    - [x] there is not form field for creating a stack. use the org name? Use the app name? - Currently we create a stack with the name `${organization.name} ${stack.type}`
  - [x] database should be provisioned after verification. App and db should be created after credit card data is entered (even before maybe, whatever is easier)

- [x] Empty app view (screen 203) (#78)
    -  [x] An un-deployed app (app with no services) should show quick checklist for deploying their app.  
    -  [x] Link out to manage SSH keys if user has none configured

- [x] [Improved styling#52](https://github.com/aptible/diesel.aptible.com/issues/52)
    - [x] Sign up flow styling
    - [x] New header and sub header styling
    - [x] App/DB Index
    - [x] App/DB Create
    - [x] Service/VHost index
    - [x] Service/VHost create
    - [x] App/DB Activity
    - [x] App/DB Deprovision

- [x] Refactor existing ember app to match new design's architecture (screens 205 - 214)
    - [x] Apps/DB index and new are now child outlets to Stack:show
    - [x] Services, Vhosts, Activity, and Deprovision are child outlets to App:show
    - [x] Activity and Deprovision are child outlets to Database:show
    - [x] Soon stacks will return rate information from API.  Consider how we'll use this with current container configuration to calculate an estimated cost of each service. (screen 212)
    - [x] service list page (without rate information, for now) (in progress: https://github.com/aptible/diesel.aptible.com/issues/62)

- [x] Paginated resources (screen 216)
    -  [x] Currently only applies to App/DB activity, but has bearing on eventual pagination of other resources and possibly compliance. (PR: #60)

- [x] User settings (design unchanged)
    - [x] SSH Keys display page (#66)
    - [x] Email/Password display page (#66)
    - [x] Name/Gravatar display page (#66)
    - [x] SSH Key page allows user to add/remove keys
    - [x] /settings/admin allows user to change email or password
    - [x] /settings/profile allows user to change name (see #69)

- [x] App show page
  - [x] Populate last deployed by.  Depends on 201-created/ember-data-hal-9000/issues/7 (PR: #88)
  - [x] Populate current git ref.  Depends on 201-created/ember-data-hal-9000/issues/7 (PR: #88)
  - [x] Copy to clipboard for domain hostname (pr #88)

- [x] Date format helper (in PR: #88 there is a `format-date` helper. See also #87)

- [x] App create page
  - [x] Handlify app handle as you type (#89)

- [x] DB create page
 - [x] Handlify db handle as you type (#89)

- [x] DB deprovision (PR: #99)

- [x] Logging (#98)
  - [x] Log drain index (screen 210)
  - [x] Log drain create (screen 211)
  - [x] Remove stack settings page, instead Logging Configure should link to log drains 

- [x] Stacks Index page #92 
- [x] Multiple Organization UX #93 

- [x] Back button issues #95 

- [x] Bootstrap Components? (issue: #107, PR #108 ) I'd like to be able to use [Tooltip](http://getbootstrap.com/javascript/#tooltips), [Popover](http://getbootstrap.com/javascript/#popovers), and [Alert](http://getbootstrap.com/javascript/#alerts) Bootstrap components, but I am not sure the best way to go about this. Angular has the popular [UI Bootstrap](http://angular-ui.github.io/bootstrap/) library to handle this.  Is there something comparable for Ember, or do we just have to write our own components?

- [x] Update page titles #94 (PR: #113)

- [x] Empty index pages need additional design #100 

- [x] Stack show page (#124)
index
  - [x] Total app containers used
  - [x] Total disk size provisioned

- [x] Forgot password functionality (@mixonic) https://github.com/aptible/diesel.aptible.com/pull/127

- [x] Unverified account view (screen 201) (#128)
    - [x] Don't block entire UX for unverified users.  Provide glimpse of provisioned account and any "apps" they provisioned in set up flow.
    - [x] Create the apps/databases but do not provision. Upon verification of a user, provision any apps/dbs they have not provisioned.
    - [x] verify that deploys check for a verified user.
    - [x] unverified users see a verify page (needs design for apps/dbs they have created)

**Comment by bantic** [comment]
moved "user settings" to completed section.
